package mernisReference;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.11.5.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



public interface TSJIServiceEvents
{
    void Starting();
    void Completed(TSJOperationResult result);
}
